login_redirect:
  default: /user
  authenticated: ''
  administrator: /en/challenge-admin-dashboard
  creator: ''
  reviewer: ''
  challenge_owner: /en/challenge-owner-dashboard
  juror: /en/challenge-judging-page
  crushit_juror: /en/challenge-judging-page-crushit
_core:
  default_config_hash: HPdrIYAmH8nz9_LVBzz1mb8Rq6r2XxdBPW59N4da4XA
