smtp_on: true
smtp_host: smtp.mailgun.org
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_username: postmaster@impact.cds-snc.ca
smtp_password: c37b5e2ce87a89856ca0fe02cf0fa6da-db1f97ba-519c3668
smtp_from: no-reply@impact.cds-snc.ca
smtp_fromname: 'Impact Canada '
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
